export const DomainErrorCode = {
  ID_NOT_LONG_ENOUGH: 'ID_NOT_LONG_ENOUGH',
  COMMENTS_COUNT_INVALID: 'COMMENT_COUNT_INVALID',
  USER_CREATION_DATE_INVALID: 'USER_CREATION_DATE_INVALID',
  FAVOURITES_COUNT_INVALID: 'FAVOURITES_COUNT_INVALID',
  USER_NAME_IS_TOO_LONG: 'USER_NAME_IS_TOO_LONG',
  USER_NAME_IS_TOO_SHORT: 'USER_NAME_IS_TOO_SHORT',
  USER_NAME_CONTAINS_INVALID_CHARACTERS: 'USER_NAME_CONTAINS_INVALID_CHARACTERS',
  PASSWORD_IS_INVALID: 'PASSWORD_IS_INVALID',
  POSTS_COUNT_INVALID: 'POSTS_COUNT_INVALID',
  PROFILE_PICTURE_IS_INVALID: 'PROFILE_PICTURE_IS_INVALID',
  USER_EMAIL_IS_INVALID: 'USER_EMAIL_IS_INVALID',
  PROPOSALS_COUNT_INVALID: 'PROPOSALS_COUNT_INVALID',
  USERNAME_IS_TOO_SHORT: 'USERNAME_IS_TOO_SHORT',
  USERNAME_IS_TOO_LONG: 'USERNAME_IS_TOO_LONG',
  USERNAME_IS_INVALID: 'USERNAME_IS_INVALID',
  HASHED_PASSWORD_TOO_SHORT: 'HASHED_PASSWORD_TOO_SHORT',
  USER_WITH_ID_ALREADY_EXISTS: 'USER_WITH_ID_ALREADY_EXISTS',
  USER_WITH_EMAIL_ALREADY_EXISTS: 'USER_WITH_EMAIL_ALREADY_EXISTS',
  USER_WITH_USERNAME_ALREADY_EXISTS: 'USER_WITH_USERNAME_ALREADY_EXISTS',
  USER_NOT_FOUND_BY_ID: 'USER_NOT_FOUND_BY_ID',
  EMAIL_AND_NEW_EMAIL_ARE_EQUAL: 'EMAIL_AND_NEW_EMAIL_ARE_EQUAL',
  NAME_AND_NEW_NAME_ARE_EQUAL: 'NAME_AND_NEW_NAME_ARE_EQUAL'
} as const

export type DomainErrorCode = (typeof DomainErrorCode)[keyof typeof DomainErrorCode]