export const TOKEN_EXPIRATION_SECS = {
  ACCESS: 15 * 60, // 15 mins
  REFRESH: 7 * 24 * 60 * 60, // 7 days
};

export const UPPER_POSTS_LIMIT = 1000000;
export const UPPER_PROPOSALS_LIMIT = 1000000;
export const UPPER_COMMENTS_LIMIT = 1000000;
export const UPPER_FAVOURITES_LIMIT = 1000000;

export const USER_NAME_CHAR_UPPER_LIMIT = 30;
export const USER_NAME_CHAR_LOWER_LIMIT = 2;

export const USERNAME_CHAR_UPPER_LIMIT = 20;
export const USERNAME_CHAR_LOWER_LIMIT = 3;

export const POST_TITLE_CHAR_UPPER_LIMIT = 30;
export const POST_TITLE_CHAR_LOWER_LIMIT = 3;
export const POST_TITLE_MAX_NEW_LINES = 1;

export const POST_DESCRIPTION_CHAR_UPPER_LIMIT = 300;
export const POST_DESCRIPTION_CHAR_LOWER_LIMIT = 10;
export const POST_DESCRIPTION_MAX_NEW_LINES = 20;

export const POST_FAVOURITES_UPPER_LIMIT = 1000000;
export const POST_COMMENTS_UPPER_LIMIT = 1000000;
export const POST_PROPOSALS_UPPER_LIMIT = 1000;

export const POST_TAGS_UPPER_LIMIT = 30;

export const PLAY_STEPS_UPPER_LIMIT = 15;
export const PLAY_STEP_ELEMENTS_UPPER_LIMIT = 30;

export const DRAFT_DESCRIPTION_CHAR_UPPER_LIMIT = 300;
export const DRAFT_DESCRIPTION_CHAR_LOWER_LIMIT = 0;
export const DRAFT_DESCRIPTION_MAX_NEW_LINES = 20;

export const DRAFT_TITLE_CHAR_UPPER_LIMIT = 30;
export const DRAFT_TITLE_CHAR_LOWER_LIMIT = 3;
export const DRAFT_TITLE_MAX_NEW_LINES = 1;

export const COMMENT_MESSAGE_UPPER_LIMIT = 300;
export const COMMENT_MESSAGE_LOWER_LIMIT = 1;
export const COMMENT_MESSAGE_MAX_NEW_LINES = 20;

export const COMMENT_FAVOURITES_UPPER_LIMIT = 100000;

export const SEARCH_POSTS_TAGS_UPPER_LIMIT = 50;
export const SEARCH_POSTS_MIN_FAVOURITES_UPPER_LIMIT = 1000000;

export const PROPOSAL_TITLE_CHAR_UPPER_LIMIT = 30;
export const PROPOSAL_TITLE_CHAR_LOWER_LIMIT = 3;
export const PROPOSAL_TITLE_MAX_NEW_LINES = 1;

export const PROPOSAL_DESCRIPTION_CHAR_UPPER_LIMIT = 300;
export const PROPOSAL_DESCRIPTION_CHAR_LOWER_LIMIT = 3;
export const PROPOSAL_DESCRIPTION_MAX_NEW_LINES = 20;

export const REPLY_PROPOSAL_HISTORY_ENTRIE_MESSAGE_UPPER_LIMIT = 300;
export const REPLY_PROPOSAL_HISTORY_ENTRIE_MESSAGE_LOWER_LIMIT = 1;
export const REPLY_PROPOSAL_HISTORY_ENTRIE_MESSAGE_MAX_NEW_LINES = 20;
