export const Token = {
  DB_CONFIG: "DB_CONFIG",
  COMMENT_REPOSITORY: "COMMENT_REPOSITORY",
  USER_REPOSITORY: "USER_REPOSITORY",
  PASSWORD_HASHER: "PASSWORD_HASHER",
  ERROR_MIDDLEWARE: "ERROR_MIDDLEWARE",
  APP: "APP",
  PASSWORD_HASHING_REPOSITORY: "PASSWORD_HASHING_REPOSITORY",
  REGISTER_USER: "REGISTER_USER",
  ENDPOINT: "ENDPOINT",
  API_DOCS: "API_DOCS",
  LOGIN_USER: "LOGIN_USER",
  TOKEN_REPOSITORY: "TOKEN_REPOSITORY",
} as const;

export type Token = (typeof Token)[keyof typeof Token];
