export const TOKEN_EXPIRATION = {
  ACCESS: 15 * 60 * 1000, // 15 mins
  REFRESH: 7 * 24 * 60 * 60 * 1000, // 7 days
};

export const UPPER_POSTS_LIMIT = 1000000;
export const UPPER_PROPOSALS_LIMIT = 1000000;
export const UPPER_COMMENTS_LIMIT = 1000000;
export const UPPER_FAVOURITES_LIMIT = 1000000;

export const USER_NAME_CHAR_UPPER_LIMIT = 30
export const USER_NAME_CHAR_LOWER_LIMIT = 2

export const USERNAME_CHAR_UPPER_LIMIT = 20
export const USERNAME_CHAR_LOWER_LIMIT = 3

export const POST_TITLE_CHAR_UPPER_LIMIT = 30
export const POST_TITLE_CHAR_LOWER_LIMIT = 3

export const POST_DESCRIPTION_CHAR_UPPER_LIMIT = 300
export const POST_DESCRIPTION_CHAR_LOWER_LIMIT = 10

export const POST_FAVOURITES_UPPER_LIMIT = 1000000
export const POST_COMMENTS_UPPER_LIMIT = 1000000
export const POST_PROPOSALS_UPPER_LIMIT = 1000

export const POST_TAGS_UPPER_LIMIT = 30

export const PLAY_STEPS_UPPER_LIMIT = 15

export const PLAY_STEP_ELEMENTS_UPPER_LIMIT = 30

