name: Test & Coverage

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set environment variables
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "TEST_MONGO_URI=${{ secrets.TEST_MONGO_URI }}" >> $GITHUB_ENV
          echo "TEST_DATABASE=${{ secrets.TEST_MONGO_DB }}" >> $GITHUB_ENV

      - name: Run tests
        run: npm run test